gnerv3
launching jobs on gnerv3, in total 1 nodes
Executing:  'python ./main.py 0 1 gnerv3' on gnerv3
Hello World From Process 0, the World Size is 1
  NumNodes: 2708
  NumEdges: 10556
  NumFeats: 1433
  NumClasses: 7
  NumTrainingSamples: 140
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.
Downloaded the graph dataset
Start Distributed GNN Training
1 DL workers are assigned to cpus [0], main process will use cpus [1, 2, 3]
Process Process-1:
Traceback (most recent call last):
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 293, in init_process
    fn(rank, size)
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 218, in run
    for input_nodes, output_nodes, blocks in dataloader:
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 1160, in __iter__
    self, super().__iter__(), num_threads=num_threads
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1042, in __init__
    w.start()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'DataLoader.enable_cpu_affinity.<locals>.init_fn'
